config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only: [:index, :new, :create, :destroy, :download] do
    member do
      get 'download'
    end
  end
  resources :words
  root "resumes#index", as: "files"
  get "/views/words/translate", to: "words#translate", as: "translate"

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  after_save :convert
  validates :name, presence: true

  def convert
    Transliterator.new(self).convert
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resumes_path, notice: "The file #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  def download
   # binding.pry
    @resume = Resume.find(params[:id])
    send_file "#{Rails.root}/public/uploads/resume/attachment/#{@resume.id}/#{@resume.id}.docx",
              :filename => "#{@resume.name}.docx",
              :type => 'text/docx; charset=utf-8',
              :x_sendfile=>true
  end

  def convert
    @resume = Resume.new
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    # before_action :all_tasks, only: [:index, :create]
    def index
      @words = Word.all
      # @word = Word.new
    end

    # def show
    #   @word = Word.find(params[:id])
    # end

    def new
      @word = Word.new
    end

    def create
      @word = Word.new(word_params)
      if @word.save
        # redirect_to :action => 'convert'
        redirect_to :action => 'translate'
        # binding.pry
      else
        render 'new'
      end
    end

    def destroy
      # @resume = Resume.find(params[:id])
      # @resume.destroy
      # redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
    end

    def convert
      @word = Word.new
    end


    def translate

    end

    private
    def word_params
      params.require(:word).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testfile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container" style="padding-top:20px;">
<%= yield %>
  </div>
</body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<meta charset="UTF-8">
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<br />

<%= link_to "New File", new_resume_path, class: "btn" %>
<%= link_to "Real-time converter", translate_path, class: "btn" %>
<br />
<br />

<table class = "table table-bordered table-striped">
  <thead>
  <tr>
    <th style='text-align:center;vertical-align:middle'>Name</th>
    <th style='text-align:center;vertical-align:middle'>Download Link</th>
    <th style='text-align:center;vertical-align:middle'>Don't keep my file</th>
  </tr>
  </thead>

  <tbody>
  <h3>Последние загруженные файлы</h3>
  <% @resumes.each do |resume| %>

    <tr>
      <td style='text-align:center;vertical-align:middle'><%= resume.name %></td>
      <td style='text-align:center;vertical-align:middle'><%= link_to "Download document", download_resume_path(resume), data: {turbolinks: false} %></td>
      <td style='text-align:center;vertical-align:middle'><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
    </tr>

  <% end %>
  </tbody>

</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <h1>Загрузите .docx файл</h1>
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/words/translate.html.erb
<h2>Введите ваш текст на кириллице: </h2>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<br />
<div ng-app="myApp" ng-controller="myCtrl">

  <%= form_for :word,:url => {:action => 'create'} do |f| %>
    <%= f.text_area :text, data: { 'ng-model' => 'text' }, id: 'input', :rows => 10, style: 'width:80%;' %><br />

    <br />
    <h2>Ваш текст на латинице</h2> <br />
    <div class="latin">
      <p ng-bind="convert(text)" class="convert"></p>
    </div>

  <% end %>

</div>